import { IsArray, IsIn, IsISO8601, IsNumber, IsOptional, IsPositive, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

const PAYMENT_METHODS = ['cash', 'card', 'ideal', 'voucher', 'split', 'other'] as const;

export class LineItemDto {
  @IsString()
  description!: string;

  @IsOptional()
  @IsString()
  category?: string;

  @IsNumber()
  quantity!: number;

  @IsNumber()
  unitPrice!: number;

  @IsNumber()
  lineNetAmount!: number;

  @IsOptional()
  rewardEligible?: boolean;
}

export class CreateTransactionDto {
  // Not @IsUUID(): production data is validated/generated by Postgres
  // (uuid column type), which does not enforce strict RFC4122 variant
  // bits the way class-validator's IsUUID does — a handful of seeded
  // IDs in this project use simplified test UUIDs that are valid
  // Postgres uuids but fail that stricter check. IsString() keeps
  // real-world flexibility; Prisma/Postgres still reject anything
  // that isn't actually a valid uuid at the database layer.
  @IsString()
  locationId!: string;

  @IsOptional()
  @IsString()
  customerId?: string;

  @IsNumber()
  @IsPositive()
  grossAmount!: number;

  @IsOptional()
  @IsNumber()
  discountAmount?: number;

  @IsOptional()
  @IsNumber()
  serviceAmount?: number;

  @IsOptional()
  @IsNumber()
  vatAmount?: number;

  @IsNumber()
  netAmount!: number;

  @IsNumber()
  totalAmount!: number;

  @IsIn(PAYMENT_METHODS)
  paymentMethod!: (typeof PAYMENT_METHODS)[number];

  @IsOptional()
  @IsISO8601()
  occurredAt?: string;

  @IsOptional()
  @IsString()
  tableReference?: string;

  @IsOptional()
  @IsString()
  externalTransactionId?: string;

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => LineItemDto)
  lineItems?: LineItemDto[];
}